name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Aftman Modules
        uses: ok-nick/setup-aftman@v0

      - name: Build plugin
        run: rojo build --output build.rbxlx build.project.json

      - name: Deploy plugin
        uses: KryptonForce102/upload-plugin
        
