name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Aftman Modules
        uses: ok-nick/setup-aftman@v0

      - name: Build Plugin
        run: rojo build --output build.rbxm build.project.json
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: build.rbxm
          archive: false
