name: Plugin Deployment

on:
  workflow_dispatch:
  
jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ok-nick/setup-aftman@v0

    - name: Build
      run: rojo build --output build.rbxlx build.project.json